apiVersion: v1
kind: Service
metadata:
  name: dropspot-service
  namespace: dropspot
spec:
  selector:
    backend: dropspot-api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
