apiVersion: v1
kind: Service
metadata:
  name: dropspot-ui-service
  namespace: dropspot
spec:
  selector:
    backend: dropspot-ui
  ports:
    - name: ui
      protocol: TCP
      port: 4501
      targetPort: 4501
