apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropspot-api-deployment
  namespace: dropspot
  labels:
    deployment: dropspot-api
spec:
  selector:
    matchLabels:
      deployment: dropspot-api
  template:
    metadata:
      labels:
        deployment: dropspot-api
        backend: dropspot-api
    spec:
      containers:
        - name: dropspot-api
          imagePullPolicy: IfNotPresent
          image: digitalgoetz/dropspot-api:0.0.2
          resources:
            limits:
              memory: 1024Mi
          ports:
            - containerPort: 3000
